require('config.options')
require('config.keymaps')

require('plugins.lsp')
require('plugins.colors')
require('plugins.treesitter')
require('plugins.neo-tree')
require('plugins.fzf')
require('plugins.wakatime')
require('plugins.mini')
require('plugins.harpoon')
require('plugins.vim-fugitive')
require('plugins.tmux')
require('plugins.gitsigns')
require('plugins.neotest')
require('plugins.dap')
